name: Run Tests with Jest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm ci  # o npm install si no tienes un package-lock.json

    - name: Run tests with Jest
      run: npx jest  # Usa npx en lugar de npm test

    - name: Fix permissions (if needed)
      run: chmod +x node_modules/.bin/jest
